version: 2.1

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: Inspect
          command: echo "I love ${FEATURE} builds"
          environment:
            FEATURE: "feat-1"

workflows:
  main:
    jobs:
      - echo
